<a href="https://colab.research.google.com/github/sanjeevan-nxtworx/Pandas/blob/main/01_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Import libraries


In [2]:
import numpy as np

###Create a numpy array from python list

In [3]:
sales = [0, 5, 155, 0, 518, 0, 1827, 628, 217, 223]
sales_array = np.array(sales)
type(sales_array)

numpy.ndarray

In [5]:
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.ndim}")
print(f"dtype: {sales_array.dtype}")

ndim: 1
shape: (10,)
size: 1
dtype: int64


###Creating a multidimensional Array

In [9]:
sales = [[10, 20, 30, 40, 50],[50, 70, 80, 90, 100]]
sales_array = np.array(sales)
sales

[[10, 20, 30, 40, 50], [50, 70, 80, 90, 100]]

In [10]:
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.ndim}")
print(f"dtype: {sales_array.dtype}")

ndim: 2
shape: (2, 5)
size: 2
dtype: int64


###Transposing an array

In [11]:
sales_array.T

array([[ 10,  50],
       [ 20,  70],
       [ 30,  80],
       [ 40,  90],
       [ 50, 100]])

###Creating an array using list comprehension

In [12]:
mylist = [x * 10 for x in range(1, 11)]
my_array = np.array(mylist)

In [13]:
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

###reshaping an array

In [14]:
my_array.reshape(5, 2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

###Creating ones and zeroes array

In [15]:
np.ones(5,)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((5, 2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [23]:
np.zeros((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.arange(10, 100, 10)  # start stop step

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
np.linspace(10, 100, 5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [27]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

###Creating an array of structured objects

In [26]:
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('score', 'f4')])
arr = np.array([('Alice', 25, 85.5), ('Bob', 30, 92.3)], dtype=dt)

print(arr['name'])  # Output: ['Alice' 'Bob']
print(arr.dtype)
# Output: [('name', '<U10'), ('age', '<i4'), ('score', '<f4')]


['Alice' 'Bob']
[('name', '<U10'), ('age', '<i4'), ('score', '<f4')]


###Converting the type of an array

In [28]:
arr = np.array([1.5, 2.3, 3.7])
int_arr = arr.astype(np.int32)  # Converts float to integer
print(int_arr)  # Output: [1 2 3]


[1 2 3]
